name: TFISpaceWeapons
main: TFISpaceWeapons.Main
version: 2.0.0
api-version: 1.18
author: GabeTrafalgar(supersquids12), BearTrafalgar(_MrUniverse)
description: Provides a variety of space themed weapon functionality. PDCs and Railguns
