name: TFIPDC
main: TFIPDC.Main
version: 1.0.0
api-version: 1.18
author: GabeTrafalgar(supersquids12), BearTrafalgar(_MrUniverse)
description: allows for fireball based weaponry capable of destroying almost any block
